src/FacultyLanding/Areas/Admin/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.AspNetCore.Hosting;
using FacultyLanding.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using System.Net.Http.Headers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Adm.Controllers
{
    [Area("Admin")]
    public class ReviewController : Controller
    {
        private readonly string _url = "http://localhost:58585/api/reviews";
        private HttpClient _client;
        private IHostingEnvironment _environment;
        private readonly ILogger<ReviewController> _logger;

        public ReviewController(IHostingEnvironment environment,
            ILogger<ReviewController> logger)
        {
            _client = new HttpClient();
            _environment = environment;
            _logger = logger;
        }

        // GET: NEWS
        public async Task<IActionResult> Index()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var task = await _client.GetAsync(_url);
            var stringResponse = await task.Content.ReadAsStringAsync();
            var reviews = JsonConvert.DeserializeObject<IEnumerable<Review>>(stringResponse).ToList();

            return View(reviews);
        }

        public IActionResult Create()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,Title,Author,Content,PhotoLink")] Review review, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (!Directory.Exists(_environment.WebRootPath + "/" + "upload/reviews/"))
                Directory.CreateDirectory(_environment.WebRootPath + "/" + "upload/reviews/");

            if (file == null)
            {
                review.PhotoLink = "https://storage.googleapis.com/prestashop/img/no_image.png";
            }
            else
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(review);
                }
                review.PhotoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, review.PhotoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            ModelState.Clear();
            this.TryValidateModel(review);

            if (ModelState.IsValid)
            {
                HttpContent content = new StringContent(JsonConvert.SerializeObject(review), Encoding.UTF8, "application/json");
                var post = await _client.PostAsync("http://localhost:58585/api/Reviews", content);

                return RedirectToAction("Index");
            }
            return View(review);
        }

        // GET: Review/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var review = JsonConvert.DeserializeObject<Review>(streamPage);

            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Review/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }
            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var review = JsonConvert.DeserializeObject<Review>(streamPage);

            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,Title,Author,Content,PhotoLink")] Review review, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id != review.ReviewId)
            {
                return NotFound();
            }
            if (file != null)
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(review);
                }
                review.PhotoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, review.PhotoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            ModelState.Clear();
            this.TryValidateModel(review);

            if (ModelState.IsValid)
            {
                try
                {
                    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpContent content = new StringContent(JsonConvert.SerializeObject(review), Encoding.UTF8, "application/json");
                    var put = await _client.PutAsync(_url + $"/{id}", content);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (review.ReviewId == 0)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(review);
        }

        // GET: Review/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var review = JsonConvert.DeserializeObject<Review>(streamPage);

            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var del = await _client.DeleteAsync(_url + $"/{id}");
            return RedirectToAction("Index");
        }

        public IActionResult Error()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            return View();
        }
    }
}

src/FacultyLanding/Areas/Api/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FacultyLanding.Models;
using Microsoft.AspNetCore.Http;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Api.Controllers
{
    [Area("Api")]
    [Route("api/Reviews")]
    public class ReviewsController : Controller
    {
        private readonly IFacultyRepository _repository;

        public ReviewsController(IFacultyRepository repo)
        {
            _repository = repo;
        }

        // GET: api/values
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<Review> news = _repository.GetAllReviews();
            return new JsonResult(news);
        }

        // GET api/values/5
        [HttpGet("{id}", Name = "GetReview")]
        public IActionResult Get(int id)
        {
            var Review = _repository.GetReview(id);
            if (Review == null || Review.ReviewId != id)
            {
                return NotFound();
            }
            return new JsonResult(Review);
        }

        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]Review review)
        {
            if (review == null || !ModelState.IsValid)
            {
                return BadRequest();
            }
            _repository.AddReview(review);
            return CreatedAtRoute("GetReview",
                new { id = review.ReviewId }, review);
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody]Review review)
        {
            if (review == null || !ModelState.IsValid)
            {
                return BadRequest();
            }
            review.ReviewId = id;

            var oldReview = _repository.GetReview(id);
            if (oldReview == null || oldReview.ReviewId != id)
            {
                return NotFound();
            }

            _repository.UpdateReview(review);
            return new NoContentResult();
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var review = _repository.GetReview(id);
            if (review == null || review.ReviewId != id)
            {
                return NotFound();
            }

            _repository.RemoveReview(id);
            return new NoContentResult();
        }
    }
}

src/FacultyLanding/Areas/Admin/Views/Review/Create.cshtml
@model FacultyLanding.Models.Review

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
             </div>
        </div>
        <div class="form-group">
            <label asp-for="Author" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Author" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Content" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhotoLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhotoLink" type="file" name="file" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/Review/Delete.cshtml
@model FacultyLanding.Models.Review

@{
    ViewData["Title"] = "AdminDelete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            Photo
        </dt>
        <dd>
            <img src="@Html.DisplayFor(model => model.PhotoLink)" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/FacultyLanding/Areas/Admin/Views/Review/Details.cshtml
@model FacultyLanding.Models.Review

@{
    ViewData["Title"] = "AdminDetails";
}

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoLink)
        </dt>
        <dd>
            <img src="@Html.DisplayFor(model => model.PhotoLink)" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ReviewId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/Review/Edit.cshtml
@model FacultyLanding.Models.Review

@{
    ViewData["Title"] = "AdminEdit";
}

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ReviewId" />
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhotoLink" class="col-md-2 control-label"></label>
            <img src="@Model.PhotoLink" />
            <div class="col-md-10">
                <input type="hidden" asp-for="PhotoLink" class="form-control" />
                <input asp-for="PhotoLink" type="file" name="file" class="form-control" />
                <span asp-validation-for="PhotoLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Author" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FacultyLanding/Areas/Admin/Views/Review/Index.cshtml
@using FacultyLanding.Models

@model IEnumerable<Review>

@{
    ViewData["Title"] = "ReviewsAdmin";
}

<p>
    <a class="btn btn-link" asp-action="Create">Create New</a>
</p>

<form asp-controller="Review" asp-action="Index" method="get">

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Author", "Index")
            </th>
            <th class="no_sort">
                @Html.ActionLink("Photo", "Index")
            </th>
            <th>
                @Html.ActionLink("Title", "Index")
            </th>
            <th>
                @Html.ActionLink("Content", "Index")
            </th>
            <th class="no_sort"></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.PhotoLink)" alt="Alternate Text" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Content)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ReviewId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ReviewId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ReviewId">Delete</a>
                </td>
            </tr>
        }

    </tbody>

</table>