src/FacultyLanding/Models/Company.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyLanding.Models
{
    public class Company
    {
        public int CompanyId { get; set; }

        [Required]
        [Url]
        [MaxLength(100)]
        public string WebsiteLink { get; set; }

        [Required]
        public string LogoLink { get; set; }
    }
}

src/FacultyLanding/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using System.Net;
using FacultyLanding.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Adm.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly string _url = "http://localhost:58585/api/companies";
        private HttpClient _client;
        private IHostingEnvironment _environment;

        public CompanyController(IHostingEnvironment environment)
        {
            _client = new HttpClient();
            _environment = environment;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var task = await _client.GetAsync(_url);
            var stringNews = await task.Content.ReadAsStringAsync();
            var Companies = (JsonConvert.DeserializeObject<IEnumerable<Company>>(stringNews)).ToList();

            return View(Companies);
        }


        public IActionResult Create()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyId,WebsiteLink,LogoLink")] Company Company, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (!Directory.Exists(_environment.WebRootPath + "/" + "upload/companies/"))
                Directory.CreateDirectory(_environment.WebRootPath + "/" + "upload/companies/");

            if (file == null)
            {
                Company.LogoLink = "https://storage.googleapis.com/prestashop/img/no_image.png";
            }
            else
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(Company);
                }
                Company.LogoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, Company.LogoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            ModelState.Clear();
            this.TryValidateModel(Company);

            if (ModelState.IsValid)
            {
                HttpContent content = new StringContent(JsonConvert.SerializeObject(Company), Encoding.UTF8, "application/json");
                var post = await _client.PostAsync(_url, content);

                return RedirectToAction("Index");
            }
            return View(Company);
        }

        public async Task<IActionResult> Details(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var Company = JsonConvert.DeserializeObject<Company>(streamPage);

            if (Company == null)
            {
                return NotFound();
            }

            return View(Company);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }
            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var Company = JsonConvert.DeserializeObject<Company>(streamPage);

            if (Company == null)
            {
                return NotFound();
            }
            return View(Company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyId,WebsiteLink,LogoLink")] Company Company, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id != Company.CompanyId)
            {
                return NotFound();
            }
            if (file != null)
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(Company);
                }
                Company.LogoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, Company.LogoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            ModelState.Clear();
            this.TryValidateModel(Company);

            if (ModelState.IsValid)
            {
                try
                {
                    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpContent content = new StringContent(JsonConvert.SerializeObject(Company), Encoding.UTF8, "application/json");
                    var put = await _client.PutAsync(_url + $"/{id}", content);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (Company.CompanyId == 0)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(Company);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var Company = JsonConvert.DeserializeObject<Company>(streamPage);

            if (Company == null)
            {
                return NotFound();
            }

            return View(Company);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var del = await _client.DeleteAsync(_url + $"/{id}");
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UnicityCheck([Bind("CompanyId,WebsiteLink,LogoLink")] Company company)
        {
            var task = await _client.GetAsync(_url);
            var stringNews = await task.Content.ReadAsStringAsync();
            var Companies = (JsonConvert.DeserializeObject<IEnumerable<Company>>(stringNews)).ToList();

            var cmp = Companies.Single(m => m.WebsiteLink == company.WebsiteLink);

            if (cmp != null)
                return Json(data: $"Url {company.WebsiteLink} already exists.");
            return Json(data: true);
        }
    }
}

src/FacultyLanding/Areas/Api/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FacultyLanding.Models;
using Microsoft.AspNetCore.Http;
using System.Net;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Api.Controllers
{
    [Area("Api")]
    [Route("api/companies")]
    public class CompaniesController : Controller
    {
        private readonly IFacultyRepository _repository;

        public CompaniesController(IFacultyRepository repo)
        {
            _repository = repo;
        }

        // GET: api/values
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<Company> Companies = _repository.GetAllCompanies();
            JsonResult CompaniesJson = new JsonResult(Companies);
            return CompaniesJson;
        }

        // GET api/values/5
        [HttpGet("{id}", Name = "GetCompany")]
        public IActionResult Get([FromRoute] int id)
        {
            var item = _repository.GetCompany(id);
            if (item == null || item.CompanyId != id)
            {
                return NotFound();
            }
            return new JsonResult(item);
        }

        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]Company item)
        {
            if (item == null || !ModelState.IsValid)
            {
                return BadRequest();
            }
            _repository.AddCompany(item);
            return CreatedAtRoute("GetCompany", new { id = item.CompanyId }, item);
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public IActionResult Put([FromRoute] int id, [FromBody]Company item)
        {
            if (item == null || !ModelState.IsValid)
            {
                return NotFound();
            }
            item.CompanyId = id;

            var oldCompany = _repository.GetCompany(id);
            if (oldCompany == null || oldCompany.CompanyId != id)
            {
                return NotFound();
            }

            _repository.UpdateCompany(item);
            return new NoContentResult();
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public IActionResult Delete([FromRoute] int id)
        {
            var todo = _repository.GetCompany(id);
            if (todo == null)
            {
                return NotFound();
            }

            _repository.RemoveCompany(todo.CompanyId);
            return new NoContentResult();
        }
    }
}

src/FacultyLanding/Areas/Admin/Views/Company/Create.cshtml
@model FacultyLanding.Models.Company

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="WebsiteLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="WebsiteLink" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LogoLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LogoLink" type="file" name="file" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/Company/Delete.cshtml
@model FacultyLanding.Models.Company

@{
    ViewData["Title"] = "AdminDelete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Website
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>
        <dt>
            Logo
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LogoLink)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/FacultyLanding/Areas/Admin/Views/Company/Details.cshtml
@model FacultyLanding.Models.Company

@{
    ViewData["Title"] = "AdminDetails";
}

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Website
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WebsiteLink)
        </dd>
        <dt>
            Logo
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LogoLink)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CompanyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/Company/Edit.cshtml
@model FacultyLanding.Models.Company

@{
    ViewData["Title"] = "AdminEdit";
}

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CompanyId" />
        <div class="form-group">
            <label asp-for="WebsiteLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="WebsiteLink" class="form-control" />
                <span asp-validation-for="WebsiteLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LogoLink" class="col-md-2 control-label"></label>
            <img src="@Model.LogoLink" />
            <div class="col-md-10">
                <input type="hidden" asp-for="LogoLink" class="form-control" />
                <input asp-for="LogoLink" type="file" name="file" class="form-control" />
                <span asp-validation-for="LogoLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FacultyLanding/Areas/Admin/Views/Company/Index.cshtml
@using FacultyLanding.Models

@model IEnumerable<Company>

@{
    ViewData["Title"] = "FactAdmin";
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Company" asp-action="Index" method="get"></form>
<table class="table">
    <thead>
        <tr>
            <th class="no_sort">
                Logo
            </th>
            <th>
                Company's website
            </th>
            <th ></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.LogoLink)" alt="Alternate Text" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WebsiteLink)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CompanyId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.CompanyId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.CompanyId">Delete</a>
                </td>
            </tr>
        }

    </tbody>

</table>