src/FacultyLanding/Models/NewsItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyLanding.Models
{
    public class NewsItem
    {
        public int NewsItemId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [MaxLength(256)]
        public string Snippet { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public string PhotoLink { get; set; }

        [Required]
        public DateTime PublicationDate { get; set; } 
    }

}

src/FacultyLanding/Areas/Admin/Controllers/NewsItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using System.Net;
using FacultyLanding.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Net.Http.Headers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Adm.Controllers
{
    [Area("Admin")]
    public class NewsItemController : Controller
    {
        private readonly string _url = "http://localhost:58585/api/newsitems";
        private HttpClient _client;
        private IHostingEnvironment _environment;

        public NewsItemController(IHostingEnvironment environment)
        {
            _client = new HttpClient();
            _environment = environment;
        }

        // GET: NEWS
        public async Task<IActionResult> Index()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var task = await _client.GetAsync(_url);
            var stringNews = await task.Content.ReadAsStringAsync();
            var news = (JsonConvert.DeserializeObject<IEnumerable<NewsItem>>(stringNews)).ToList();

            return View(news);
        }

        public IActionResult Create()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NewsItemId,Title,Snippet,Content,PhotoLink,PublicationDate")] NewsItem ni, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (!Directory.Exists(_environment.WebRootPath + "/" + "upload/news/"))
                Directory.CreateDirectory(_environment.WebRootPath + "/" + "upload/news/");

            if (file == null)
            {
                ni.PhotoLink = "https://storage.googleapis.com/prestashop/img/no_image.png";
            }
            else
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(ni);
                }
                ni.PhotoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, ni.PhotoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            ModelState.Clear();
            this.TryValidateModel(ni);

            if (ModelState.IsValid)
            {
                HttpContent content = new StringContent(JsonConvert.SerializeObject(ni), Encoding.UTF8, "application/json");
                var post = await _client.PostAsync(_url, content);

                return RedirectToAction("Index");
            }
            return View(ni);
        }

        // GET: NewsItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var ni = JsonConvert.DeserializeObject<NewsItem>(streamPage);

            if (ni == null)
            {
                return NotFound();
            }

            return View(ni);
        }

        // GET: NewsItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }
            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var ni = JsonConvert.DeserializeObject<NewsItem>(streamPage);

            if (ni == null)
            {
                return NotFound();
            }
            return View(ni);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NewsItemId,Title,Snippet,Content,PhotoLink,PublicationDate")] NewsItem ni, IFormFile file)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id != ni.NewsItemId)
            {
                return NotFound();
            }
            if (file != null)
            {
                List<string> validExtensions = new List<string> { ".jpg", ".png", ".jpeg" };
                var extension = Path.GetExtension(file.FileName);
                if (!validExtensions.Contains(extension))
                {
                    ModelState.AddModelError(String.Empty, "Valid extensions are .jpg, .png, .jpeg");
                    return View(ni);
                }
                ni.PhotoLink = String.Concat("upload/professors/", file.FileName);

                using (var fileStream = new FileStream(
                Path.Combine(_environment.WebRootPath, ni.PhotoLink), FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpContent content = new StringContent(JsonConvert.SerializeObject(ni), Encoding.UTF8, "application/json");
                    var put = await _client.PutAsync(_url + $"/{id}", content);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (ni.NewsItemId == 0)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(ni);
        }

        // GET: NewsItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return NotFound();
            }

            var task = await _client.GetAsync(_url + $"/{id}");
            var streamPage = await task.Content.ReadAsStringAsync();

            var ni = JsonConvert.DeserializeObject<NewsItem>(streamPage);

            if (ni == null)
            {
                return NotFound();
            }

            return View(ni);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            var del = await _client.DeleteAsync(_url + $"/{id}");
            return RedirectToAction("Index");
        }

        public IActionResult Error()
        {
            var log = HttpContext.Session.GetString("Log");

            if (log != "Admin")
                return RedirectToAction("Login", "Home");

            return View();
        }
    }
}

src/FacultyLanding/Areas/Api/Controllers/NewsItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FacultyLanding.Models;
using Microsoft.AspNetCore.Http;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FacultyLanding.Areas.Api.Controllers
{
    [Area("Api")]
    [Route("api/newsitems")]
    public class NewsItemsController : Controller
    {
        private readonly IFacultyRepository _repository;

        public NewsItemsController(IFacultyRepository repo)
        {
            _repository = repo;
        }

        // GET: api/values
        [HttpGet]
        public IActionResult Get()
        {
            IEnumerable<NewsItem> news = _repository.GetAllNewsItems();
            return new JsonResult(news);
        }

        // GET api/values/5
        [HttpGet("{id}", Name = "GetNewsItem")]
        public IActionResult Get(int id)
        {
            var newsItem = _repository.GetNewsItem(id);
            if (newsItem == null || newsItem.NewsItemId != id)
            {
                return NotFound();
            }
            return new JsonResult(newsItem);
        }

        // POST api/values
        [HttpPost]
        public IActionResult Post([FromBody]NewsItem ni)
        {
            if (ni == null || !ModelState.IsValid)
            {
                return BadRequest();
            }
            _repository.AddNewsItem(ni);
            return CreatedAtRoute("GetNewsItem",
                new { id = ni.NewsItemId }, ni);
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody]NewsItem ni)
        {
            if (ni == null || !ModelState.IsValid)
            {
                return BadRequest();
            }
            ni.NewsItemId = id;

            var oldNewsItem = _repository.GetNewsItem(id);
            if (oldNewsItem == null || oldNewsItem.NewsItemId != id)
            {
                return NotFound();
            }

            _repository.UpdateNewsItem(ni);
            return new NoContentResult();
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public IActionResult Delete(int id)
        {
            var ni = _repository.GetNewsItem(id);
            if (ni == null || ni.NewsItemId != id)
            {
                return NotFound();
            }

            _repository.RemoveNewsItem(id);
            return new NoContentResult();
        }
    }
}

src/FacultyLanding/Areas/Admin/Views/NewsItem/Create.cshtml
@model FacultyLanding.Models.NewsItem

@{
    ViewData["Title"] = "Create";
}

<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>NewsItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
             </div>
        </div>
        <div class="form-group">
            <label asp-for="Snippet" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Snippet" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Content" class="form-control" >
                </textarea>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhotoLink" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PhotoLink" type="file" name="file" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/NewsItem/Delete.cshtml
@model FacultyLanding.Models.NewsItem

@{
    ViewData["Title"] = "AdminDelete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NewsItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Snippet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Snippet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/FacultyLanding/Areas/Admin/Views/NewsItem/Details.cshtml
@model FacultyLanding.Models.NewsItem

@{
    ViewData["Title"] = "AdminDetails";
}

<div>
    <h4>NewsItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.Raw(Model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoLink)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Snippet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Snippet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.NewsItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/FacultyLanding/Areas/Admin/Views/NewsItem/Edit.cshtml
@model FacultyLanding.Models.NewsItem

@{
    ViewData["Title"] = "AdminEdit";
}

<form asp-action="Edit" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>NewsItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="NewsItemId" />
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Content" class="form-control" ></textarea>
                <span asp-validation-for="Content" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhotoLink" class="col-md-2 control-label"></label>
            <img src="@Model.PhotoLink" />
            <div class="col-md-10">
                <input type="hidden" asp-for="PhotoLink" class="form-control" />
                <input asp-for="PhotoLink" type="file" name="file" class="form-control" />
                <span asp-validation-for="PhotoLink" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PublicationDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PublicationDate" class="form-control" />
                <span asp-validation-for="PublicationDate" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Snippet" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Snippet" class="form-control" />
                <span asp-validation-for="Snippet" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/FacultyLanding/Areas/Admin/Views/NewsItem/Index.cshtml
@using FacultyLanding.Models

@model IEnumerable<NewsItem>

@{
    ViewData["Title"] = "NewsAdmin";
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="NewsItem" asp-action="Index" method="get">

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Title", "Index")
            </th>
            <th>
                @Html.ActionLink("Snippet", "Index")
            </th>
            <th class="no_sort">
                @Html.ActionLink("PhotoLink", "Index")
            </th>
            <th>
                @Html.ActionLink("PublicationDate", "Index")
            </th>
            <th class="no_sort"></th>
        </tr>
    </thead>
    <tbody>


        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Snippet)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.PhotoLink)" alt="Alternate Text" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicationDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.NewsItemId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.NewsItemId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.NewsItemId">Delete</a>
                </td>
            </tr>
        }

    </tbody>

</table>